// web-components-reuse/vue-app/src/components/MarketsComparatorInput.vue
<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import type { Asset, Currency } from '../data/api';

interface Props {
    assets: Asset[];
    currencies: Currency[];

    onChosenMarketSizeChange: (assetOrCurrency: string, marketSize: number) => void;
}

const { assets, currencies, onChosenMarketSizeChange } = defineProps<Props>();

const assetOrCurrencyInput = ref<string>();
const curencyTurnoverInputMultiplier = ref<number>(1);

const assetsOrCurrencyOptions = computed<string[]>(() => {
    const options: string[] = [];
    assets.forEach(a => options.push(a.name));
    currencies.forEach(c => options.push(c.code.name));
    return options;
});

const assetOrCurrencyClickHandler = (ac: string) => {
    assetOrCurrencyInput.value = ac;
    calculateChosenMarketSizeChange();
};

const calculateChosenMarketSizeChange = () => {
    if (!assetOrCurrencyInput.value) {
        return;
    }

    const assetInput = assets.find(a => a.name == assetOrCurrencyInput.value);
    const currencyInput = currencies.find(c => c.code.name == assetOrCurrencyInput.value);

    const inputMarketSize = assetInput ? assetInput.marketSize : currencyInput!!.marketSize * curencyTurnoverInputMultiplier.value;

    console.log("Input asset or currency...", assetInput, currencyInput);
    console.log("Market size...", inputMarketSize);

    onChosenMarketSizeChange(assetOrCurrencyInput.value, inputMarketSize);
};

const isAsset = (assetOrCurrency?: string): boolean => assetOrCurrency ? assets.find(a => a.name == assetOrCurrency) != undefined : false;
const isCurrency = (assetOrCurrency?: string): boolean => assetOrCurrency ? currencies.find(c => c.code.name == assetOrCurrency) != undefined : false;

watch(curencyTurnoverInputMultiplier, () => calculateChosenMarketSizeChange());
watch(() => assets, () => {
    calculateChosenMarketSizeChange();
});
watch(() => currencies, () => {
    calculateChosenMarketSizeChange();
})

</script>

<template>
    <drop-down-container>
        <div>
            <span data-drop-down-anchor>{{ assetOrCurrencyInput ?? 'Asset/Currency' }}</span>
            <span v-if="isAsset(assetOrCurrencyInput)" class="mx-2">market size</span>
            <span v-else-if="isCurrency(assetOrCurrencyInput)">
                <input class="mx-2 px-2 max-w-[75px]" v-model="curencyTurnoverInputMultiplier">
                <span>days turnover</span>
            </span>
        </div>
        <ul class="border-1 rounded cursor-pointer bg-white max-h-[350px] overflow-y-auto overflow-x-none"
            data-drop-down-options>
            <li class="p-2 border-b-1 last:border-0" v-for="ac in assetsOrCurrencyOptions"
                @click="() => assetOrCurrencyClickHandler(ac)">
                {{ ac }}</li>
        </ul>
    </drop-down-container>
</template>

// web-components-reuse/vue-app/src/components/lib/markets-comparator-input.js
class MarketsComparatorInput extends HTMLElement {

    _assets = [];
    _currencies = [];
    _assetOrCurrencyOptions = [];
    _onChosenMarketSizeChange = (assetOrCurrency, marketSize) => { };

    set assets(value) {
        this._assets = value;
        this._recalculateAssetOrCurrencyOptions();
        this._rerenderOptionsHTML();
    }

    set currencies(value) {
        this._currencies = value;
        this._recalculateAssetOrCurrencyOptions();
        this._rerenderOptionsHTML();
    }

    _assetOrCurrencyInput = undefined;

    connectedCallback() {
        console.log("Connected callback!");
        this._render();
        console.log("UL? ", this.querySelector("ul"));
    }

    _render() {
        this.innerHTML = `
        <drop-down-container>
            <div>
                <span data-drop-down-anchor>${this._assetOrCurrencyInput ?? 'Asset/Currency'}</span>
            </div>
            <ul class="border-1 rounded cursor-pointer bg-white max-h-[350px] overflow-y-auto overflow-x-none" data-drop-down-options>
                ${this._optionsHTML()}
            </ul>
        </drop-down-container>
        `;
    }

    _optionsHTML() {
        return this._assetOrCurrencyOptions.map(o =>
            `<li class="p-2 border-b-1 last:border-0" onclick="assetOrCurrencyClickHandler(o)">${o.name}</li>`)
            .join('\n');
    }

    _rerenderOptionsHTML() {
        const optionsContainer = this.querySelector("ul");
        if (optionsContainer) {
            optionsContainer.innerHTML = this._optionsHTML();
        }
    }

    _isAsset(assetOrCurrency) {
        return assetOrCurrency ? this._assets.find(a => a.name == assetOrCurrency) : false;
    }

    _isCurrency(assetOrCurrency) {
        return assetOrCurrency ? this._currencies.find(c => c.name == assetOrCurrency) : false;
    }

    _recalculateAssetOrCurrencyOptions() {
        const assetOrCurrencyOptions = [];
        this._assets.forEach(a => assetOrCurrencyOptions.push(a));
        this._currencies.forEach(c => assetOrCurrencyOptions.push(c));
        this._assetOrCurrencyOptions = assetOrCurrencyOptions;
    }
}

export function register() {
    customElements.define("markets-comparator-input-wc", MarketsComparatorInput);
}
