// web-components-reuse/react-app/src/App.tsx
import { useEffect } from "react";
import { useTranslation } from "react-i18next";
import Home from "./components/Home";

export default function App() {
  const { t } = useTranslation();

  useEffect(() => {
    document.addEventListener('events.show-error-modal', e => {
      const { error } = (e as CustomEvent).detail;
      document.dispatchEvent(new CustomEvent('em.show', {
        detail: {
          title: t('errors.title'),
          error: t('errors.' + error)
        }
      }));
    });
  }, []);

  return (
    <>
      <Home />
      <error-modal></error-modal>
    </>
  )
}

// web-components-reuse/vue-app/src/App.vue
<script setup lang="ts">
import { onMounted } from 'vue';
import { useI18n } from 'vue-i18n';
import Home from './components/Home.vue';

const { t } = useI18n();

onMounted(() => {
  document.addEventListener('events.show-error-modal', e => {
    const { error } = (e as CustomEvent).detail;
    document.dispatchEvent(new CustomEvent('em.show', {
      detail: {
        title: t('errors.title'),
        error: t('errors.' + error)
      }
    }));
  });
});

</script>

<template>
  <Home />
  <error-modal></error-modal>
</template>

<style scoped></style>
